# Generated by Django 5.2.17 on 2026-08-24 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lti1p3_tool_config", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deployment_id", models.CharField(max_length=255)),
                (
                    "context_id",
                    models.CharField(
                        help_text="Claim estándar 'context.id' de LTI — es el identificador de curso de Canvas.",
                        max_length=255,
                    ),
                ),
                (
                    "canvas_course_id",
                    models.CharField(
                        blank=True,
                        help_text="Opcional: 'custom_canvas_course_id' si el Developer Key lo expone.",
                        max_length=255,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "token_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Límite de tokens por estudiante en este curso. Vacío = usar el valor por defecto global.",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lti_tool",
                    models.ForeignKey(
                        help_text="Plataforma (Developer Key) desde la que se lanzó este curso.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="courses",
                        to="lti1p3_tool_config.ltitool",
                    ),
                ),
            ],
            options={
                "ordering": ["title", "context_id"],
                "unique_together": {("lti_tool", "deployment_id", "context_id")},
            },
        ),
        migrations.CreateModel(
            name="LtiLaunchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issuer", models.CharField(blank=True, max_length=255)),
                ("client_id", models.CharField(blank=True, max_length=255)),
                ("sub", models.CharField(blank=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                ("validated", models.BooleanField(default=False)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lti_tool",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="launch_logs",
                        to="lti1p3_tool_config.ltitool",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deployment_id", models.CharField(max_length=255)),
                (
                    "sub",
                    models.CharField(
                        help_text="Claim estándar 'sub' — identificador opaco y estable del usuario en esa plataforma.",
                        max_length=255,
                    ),
                ),
                (
                    "canvas_user_id",
                    models.CharField(
                        blank=True,
                        help_text="Opcional: 'custom_canvas_user_id' si el Developer Key lo expone.",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lti_tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="lti1p3_tool_config.ltitool",
                    ),
                ),
            ],
            options={
                "unique_together": {("lti_tool", "deployment_id", "sub")},
            },
        ),
        migrations.CreateModel(
            name="CourseEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_instructor",
                    models.BooleanField(
                        default=False,
                        help_text="Si el rol LTI incluye Instructor — pensado para eximir del límite de tokens.",
                    ),
                ),
                ("chat_enabled", models.BooleanField(default=True)),
                ("limit_reached_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="lti_tool.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="lti_tool.student",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "course")},
            },
        ),
    ]
