# Generated by Django 5.2.17 on 2026-08-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_tool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='section_ids',
            field=models.CharField(blank=True, help_text="'custom_canvas_course_section_ids' si el Developer Key lo expone (separados por coma).", max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, help_text="Claim estándar 'email' — requiere Privacy Level 'Public' (o 'Email only') en el Developer Key.", max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='login_id',
            field=models.CharField(blank=True, help_text="Usuario institucional ('custom_canvas_user_login_id') si el Developer Key lo expone.", max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, help_text="Claim estándar 'name' — requiere Privacy Level 'Public' en el Developer Key.", max_length=255),
        ),
    ]
