# Generated by Django 5.2.17 on 2026-08-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_tool', '0002_courseenrollment_section_ids_student_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ags_lineitem_url',
            field=models.CharField(blank=True, help_text='Line item ya creado/reusado para la actividad del Tutor IA en este curso.', max_length=1024),
        ),
        migrations.AddField(
            model_name='course',
            name='ags_lineitems_url',
            field=models.CharField(blank=True, help_text="Claim AGS 'endpoint.lineitems' — URL para crear/listar line items del curso.", max_length=1024),
        ),
        migrations.AddField(
            model_name='course',
            name='ags_scope',
            field=models.JSONField(blank=True, default=list, help_text="Scopes AGS otorgados por Canvas (claim 'endpoint.scope')."),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='graded_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo se envió la nota de completitud a Canvas (AGS). Vacío = todavía no.', null=True),
        ),
    ]
