# Generated by Django 5.2.17 on 2026-08-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_tool', '0003_course_ags_lineitem_url_course_ags_lineitems_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='show_course_token_usage',
            field=models.BooleanField(default=True, help_text='Muestra en el chat cuántos tokens ha consumido el estudiante en total en este curso (un número, sin el límite configurado ni barra de progreso).'),
        ),
        migrations.AddField(
            model_name='course',
            name='show_unit_token_count',
            field=models.BooleanField(default=False, help_text='La barra de progreso de cada unidad siempre muestra el porcentaje de Clara. Marca esto para que además se le muestre al estudiante el número de tokens consumidos/presupuesto.'),
        ),
    ]
