# Generated by Django 5.2.17 on 2026-09-02 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_tool', '0004_course_show_course_token_usage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePageGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momento', models.CharField(help_text="Mismo valor que apps.chat.models.ClaraMoment.MOMENTO_CHOICES (p. ej. 'unidad_1').", max_length=20)),
                ('canvas_page_url', models.CharField(help_text="Slug de la página de Canvas a desbloquear — el 'url_or_id' que aparece en /courses/:id/pages/<esto>, p. ej. 'unidad-1-profundiza'.", max_length=255)),
                ('locked_at', models.DateTimeField(blank=True, help_text='Cuándo se puso only_visible_to_overrides=true en esta página (setup inicial). Vacío = todavía no.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_gates', to='lti_tool.course')),
            ],
            options={
                'unique_together': {('course', 'momento')},
            },
        ),
    ]
