# Generated by Django 5.2.17 on 2026-09-03 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lti_tool', '0005_coursepagegate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursepagegate',
            unique_together={('course', 'momento', 'canvas_page_url')},
        ),
    ]
