# Generated by Django 5.2.17 on 2026-09-04 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_tool', '0006_alter_coursepagegate_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursepagegate',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='coursepagegate',
            name='icon',
            field=models.CharField(default='lock', help_text="Nombre del ícono Font Awesome solid, p. ej. 'layer-group', 'pen-to-square', 'comments'.", max_length=50),
        ),
        migrations.AddField(
            model_name='coursepagegate',
            name='label',
            field=models.CharField(blank=True, help_text='Texto del botón en la franja de nav (ver gate_nav.html) — vacío para un ícono solo.', max_length=50),
        ),
        migrations.AddField(
            model_name='coursepagegate',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Orden de aparición en la franja del nav (menor primero).'),
        ),
    ]
