# Generated by Django 5.2.17 on 2026-09-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_tool', '0007_alter_coursepagegate_options_coursepagegate_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultPageGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momento', models.CharField(help_text="Mismo valor que apps.chat.models.ClaraMoment.MOMENTO_CHOICES (p. ej. 'unidad_1').", max_length=20)),
                ('canvas_page_url', models.CharField(help_text="Slug de la página a desbloquear en cualquier curso nuevo, p. ej. 'unidad-1-profundiza'.", max_length=255)),
                ('label', models.CharField(blank=True, max_length=50)),
                ('icon', models.CharField(default='lock', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['momento', 'order', 'id'],
                'unique_together': {('momento', 'canvas_page_url')},
            },
        ),
    ]
