# Generated by Django 5.2.17 on 2026-08-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "Estudiante"),
                            ("assistant", "Agente"),
                            ("system", "Sistema"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("tokens_prompt", models.PositiveIntegerField(default=0)),
                ("tokens_completion", models.PositiveIntegerField(default=0)),
                ("tokens_total", models.PositiveIntegerField(default=0)),
                ("n8n_execution_id", models.CharField(blank=True, max_length=255)),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activa"),
                            ("limited", "Límite alcanzado"),
                            ("closed", "Cerrada"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-last_activity_at"],
            },
        ),
        migrations.CreateModel(
            name="N8nFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Identificador interno, p. ej. WF3_CLARA.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "webhook_url",
                    models.URLField(help_text="URL del webhook de producción en n8n."),
                ),
                (
                    "shared_secret",
                    models.CharField(
                        help_text="Valor enviado en el header X-Internal-Token — debe coincidir con el que valida el workflow en n8n.",
                        max_length=255,
                    ),
                ),
                ("timeout_seconds", models.PositiveIntegerField(default=40)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "momento_tipo",
                    models.CharField(
                        choices=[
                            ("bienvenida", "Bienvenida"),
                            ("diagnostico", "Diagnóstico"),
                            ("cierre", "Cierre de curso"),
                            ("libre", "Conversación libre"),
                        ],
                        default="libre",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Texto que ve el estudiante, p. ej. 'Resolver dudas del módulo 3'.",
                        max_length=255,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="TokenUsageLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tokens_total",
                    models.IntegerField(
                        help_text="Puede ser negativo para ajustes manuales de crédito."
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
