# Generated by Django 5.2.17 on 2026-08-24 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0001_initial"),
        ("lti_tool", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_sessions",
                to="lti_tool.courseenrollment",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat.chatsession",
            ),
        ),
        migrations.AddField(
            model_name="prompttemplate",
            name="course",
            field=models.ForeignKey(
                blank=True,
                help_text="Vacío = plantilla global, disponible en cualquier curso.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="templates",
                to="lti_tool.course",
            ),
        ),
        migrations.AddField(
            model_name="prompttemplate",
            name="n8n_flow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="templates",
                to="chat.n8nflow",
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sessions",
                to="chat.prompttemplate",
            ),
        ),
        migrations.AddField(
            model_name="tokenusageledger",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="token_ledger",
                to="lti_tool.courseenrollment",
            ),
        ),
        migrations.AddField(
            model_name="tokenusageledger",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ledger_entries",
                to="chat.chatmessage",
            ),
        ),
    ]
