# Generated by Django 5.2.17 on 2026-08-26 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
        ('lti_tool', '0003_course_ags_lineitem_url_course_ags_lineitems_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaraMoment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momento', models.CharField(choices=[('bienvenida', 'Bienvenida'), ('unidad_1', 'Unidad 1'), ('unidad_2', 'Unidad 2'), ('cierre', 'Cierre de curso')], max_length=20)),
                ('pregunta_id', models.CharField(blank=True, help_text="Id de la pregunta detonadora en Supabase (campo 'pregunta_id' de /clara/apertura).", max_length=255)),
                ('mensajes_usados', models.PositiveIntegerField(default=0)),
                ('limite', models.PositiveIntegerField(default=8)),
                ('puede_avanzar', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clara_moments', to='lti_tool.courseenrollment')),
            ],
            options={
                'ordering': ['-last_activity_at'],
                'unique_together': {('enrollment', 'momento')},
            },
        ),
        migrations.CreateModel(
            name='ClaraMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Estudiante'), ('assistant', 'Clara')], max_length=20)),
                ('content', models.TextField()),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.claramoment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
