# Generated by Django 5.2.17 on 2026-08-27 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_claramoment_claramessage'),
        ('lti_tool', '0003_course_ags_lineitem_url_course_ags_lineitems_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claramoment',
            name='tokens_used',
            field=models.PositiveIntegerField(default=0, help_text='Suma de tokens consumidos en este momento (independiente del ledger de tokens del curso).'),
        ),
        migrations.AlterField(
            model_name='claramoment',
            name='limite',
            field=models.PositiveIntegerField(default=8, help_text='Tope de mensajes vigente para este momento (copiado de ClaraMomentLimit al momento de cada turno).'),
        ),
        migrations.CreateModel(
            name='ClaraMomentLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momento', models.CharField(choices=[('bienvenida', 'Bienvenida'), ('unidad_1', 'Unidad 1'), ('unidad_2', 'Unidad 2'), ('cierre', 'Cierre de curso')], max_length=20)),
                ('message_limit', models.PositiveIntegerField(default=8, help_text='Máximo de mensajes del estudiante en este momento. El tope real de n8n es 8 — ver nota arriba.')),
                ('token_limit', models.PositiveIntegerField(blank=True, help_text='Máximo de tokens consumidos en este momento. Vacío = sin tope propio (solo aplica el límite de tokens del curso).', null=True)),
                ('closing_message', models.CharField(blank=True, help_text='Mensaje que ve el estudiante al alcanzar el límite. Vacío = usa el mensaje por defecto.', max_length=500)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clara_moment_limits', to='lti_tool.course')),
            ],
            options={
                'verbose_name': 'Límite de Clara por unidad',
                'verbose_name_plural': 'Límites de Clara por unidad',
                'unique_together': {('course', 'momento')},
            },
        ),
    ]
