# Generated by Django 5.2.17 on 2026-08-27 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_claramoment_tokens_used_alter_claramoment_limite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claramomentlimit',
            name='closing_message',
            field=models.CharField(blank=True, help_text='Aviso del sistema que ve el estudiante si Django corta la conversación (tope de tokens, o intento posterior al límite de mensajes) — no es una respuesta de Clara. Vacío = usa el mensaje por defecto.', max_length=500),
        ),
        migrations.AlterField(
            model_name='claramomentlimit',
            name='message_limit',
            field=models.PositiveIntegerField(default=8, help_text='Máximo de mensajes del estudiante en este momento. El mensaje que llega a este número SÍ se manda a n8n (para que él dé el cierre); los intentos posteriores ya no se envían. El tope real del flujo de n8n es 8 — un valor mayor o igual no tiene efecto propio.'),
        ),
    ]
