# Generated by Django 5.2.17 on 2026-08-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_claramomentlimit_closing_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claramoment',
            name='porcentaje_usado',
            field=models.PositiveIntegerField(default=0, help_text="Porcentaje de presupuesto consumido, tal como lo reporta n8n (campo 'porcentaje_usado') — controla la barra de progreso."),
        ),
        migrations.AddField(
            model_name='claramoment',
            name='presupuesto',
            field=models.PositiveIntegerField(blank=True, help_text="Presupuesto de tokens de la unidad, tal como lo reporta n8n (campo 'presupuesto'). Vacío hasta el primer turno real.", null=True),
        ),
        migrations.AlterField(
            model_name='claramoment',
            name='limite',
            field=models.PositiveIntegerField(default=8, help_text="Campo 'limite' que reporta n8n — hoy vestigial, el presupuesto real es por tokens (ver abajo)."),
        ),
        migrations.AlterField(
            model_name='claramoment',
            name='tokens_used',
            field=models.PositiveIntegerField(default=0, help_text="Campo 'tokens_usados' (acumulado) que reporta n8n para este momento — no es un conteo propio de Django."),
        ),
        migrations.DeleteModel(
            name='ClaraMomentLimit',
        ),
    ]
