# Generated by Django 5.2.17 on 2026-09-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_claramoment_porcentaje_usado_claramoment_presupuesto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claramoment',
            name='page_unlocked_at',
            field=models.DateTimeField(blank=True, help_text="Cuándo se agregó al estudiante al 'Asignar acceso' de la página de Canvas configurada para este momento (ver lti_tool.CoursePageGate). Vacío = todavía no.", null=True),
        ),
    ]
